name: EarlybazeWallet
description: Earlybaze Wallet App

version: 1.0.0+2

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  get: ^4.6.5
  logger: ^1.0.0
  dio: ^5.1.1
  intl: ^0.18.1
  get_storage: ^2.0.3
  intl_phone_field: 3.1.0
  pinput: ^2.2.31
  lottie:
  file_picker: ^5.2.11
  flutter_easyloading: ^3.0.5
  device_info_plus: ^9.1.1
  package_info_plus: ^3.1.2
  flutter_html: ^3.0.0-beta.2
  image_picker: ^0.8.7+4
  flutter_rating_bar: ^4.0.1
  open_file: ^3.3.2
  image_cropper: ^3.0.3
  flutter_screenutil: ^5.8.4
  colorful_safe_area: ^1.0.0
  fancy_shimmer_image: ^2.0.2
  geocoding: ^2.1.0
  google_maps_flutter: ^2.4.0
  geolocator: ^9.0.2
  location: ^5.0.1
  google_place: 0.4.7
  flutter_google_places: ^0.3.0
  flutter_local_notifications: 9.5.3+1
  navigation_history_observer:
  firebase_core: ^2.14.0
  firebase_messaging:
  permission_handler: ^10.2.0
  grouped_list:
  multi_select_flutter: ^4.1.3
  getwidget: ^3.1.1
  dropdown_button2: 1.9.2
  auto_size_text: ^3.0.0
  path_provider: ^2.0.1
  cached_network_image:
  connectivity_plus:
  the_apple_sign_in: ^1.1.1
  slidable_button: ^3.0.0+1
  carousel_slider: ^4.2.1
  action_slider: ^0.7.0
  slide_to_act_reborn: ^3.0.0
  draggable_bottom_sheet: ^1.0.2
  interactive_bottom_sheet: ^1.0.0
  slider_button: ^2.0.0
  otp_pin_field: ^1.2.2
  flutter_launcher_icons: ^0.13.1
  simple_html_css:
  flutter_share:
  image_gallery_saver: ^2.0.3
  open_document: ^1.0.7
  flutter_file_downloader: ^1.2.1
  in_app_review: ^2.0.8
  url_launcher: ^6.2.2
  easy_pdf_viewer: ^1.0.7
  sn_progress_dialog: ^1.1.3
 # open_filex: ^4.3.4
  flutter_downloader: ^1.11.6
  flutter_logger:
    path: flutter_logger
  flutter_slidable:
  change_app_package_name: ^1.1.0





dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: 2.3.3

#flutter_launcher_icons:
#    android: "launcher_icon"
#    image_path: "assets/icons/ic_launcher.png"
#    min_sdk_android: 21
#    resize_behavior: shrink_only


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/fonts/
    - assets/lottieFiles/

  fonts:
    - family: sfPro
      fonts:
        - asset: assets/fonts/FontsFree-Net-SFProText-Regular.ttf
          weight: 400

    - family: barnaulGrotesk
      fonts:
        - asset: assets/fonts/Barnaul-Grotesk-W00-Regular.ttf
          weight: 400

    - family: lexend
      fonts:
        - asset: assets/fonts/Lexend-Regular.ttf
          weight: 400


    - family: Inter
      fonts:
        - asset: assets/fonts/PublicSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/PublicSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/PublicSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/PublicSans-Bold.ttf
          weight: 700
